# Change to true for Disqus comments & add your own discus_shortname
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Blog', folder: 'pages', file: 'blog.html'}
- {name: 'Route', folder: 'pages', file: 'map.html'}
- {name: 'Contact us', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/millyread'}
- {icon: 'instagram', link: 'https://instagram.com/readcycleread'}
- {icon: 'envelope', link: 'mailto:julian.read@outlook.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
