# Change to true for Disqus comments & add your own discus_shortname
disqus:
  comments: true
  disqus_shortname: 'readcycleread'

menu:
- {name: 'Blog', folder: 'pages', file: 'blog/index.html'}
- {name: 'Route', folder: 'pages', file: 'map.html'}
- {name: 'Gear', folder: 'pages', file: 'gearlist.html'}
- {name: 'Heroes', folder: 'pages', file: 'heroes.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fab fa-twitter', link: 'https://twitter.com/millyread'}
- {icon: 'fab fa-instagram', link: 'https://instagram.com/readcycleread'}
- {icon: 'fas fa-envelope', link: 'mailto:readcycleread@outlook.com'}
- {icon: 'fab fa-strava', link: 'https://www.strava.com/athletes/26718658'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
